theme: jekyll-theme-time-machine
source: .
baseurl: "/carnetDesCaracteres"
# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty


# Setup
title:               Caractères et Moeurs de ce temps
tagline:             'XLS'
description:         'Morale et Politique au XXIe siècle'
url:                 https://humanitesnumeriques.github.io/carnetDesCaracteres/
baseurl:             '/carnetDesCaracteres'
paginate:            5

# About/contact
author:
  name:              XLS
  url:               https://twitter.com/xsalvador
  email:            

# Custom vars
version:             1.0.0
